# Control file for continuous integration testing at http://travis-ci.org/

# ignore release tags
branches:
  except:
    /^v\d+\.\d+(\.\d+)?(-\S*)?$/  

language: c

jobs:
  include:
    - name: "x86 mingw c89"
      compiler: mingw-x86
      addons:
        packages:
          - g++-multilib # sys/cdefs.h
      env: ARCH=x86 BUILD=c89

    - name: "x64 mingw c89"
      compiler: mingw-x64
      env: ARCH=x64 BUILD=c89

    - name: "x86 linux c89"
      os: linux
      compiler: gcc
      addons:
        packages:
          - g++-multilib # sys/cdefs.h
      env: ARCH=x86 BUILD=c89

    - name: "x64 linux c89"
      os: linux
      compiler: gcc
      env: ARCH=x64 BUILD=c89

    - name: "x64 linux retroarch"
      os: linux
      compiler: gcc-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
      env:
         - ARCH=x64 BUILD=retroarch CC=gcc-8
         - MATRIX_EVAL="CC=gcc-8"

before_install:
    - eval "${MATRIX_EVAL}"

script: make -C test ARCH=$ARCH BUILD=$BUILD runtests
