# Control file for continuous integration testing at http://travis-ci.org/

# ignore release tags
branches:
  except:
    /^v\d+\.\d+(\.\d+)?(-\S*)?$/  

language: c

addons:
  packages:
    - g++-multilib # sys/cdefs.h

jobs:
  include:
    - name: "x86 mingw c89"
      compiler: i686-w64-mingw32-gcc
      addons:
        packages:
          - g++-multilib # sys/cdefs.h
      env: ARCH=x86 BUILD=c89

    - name: "x64 mingw c89"
      compiler: i686-w64-mingw64-gcc
      env: ARCH=x64 BUILD=c89

    - name: "x86 linux c89"
      os: linux
      compiler: gcc
      env: ARCH=x86 BUILD=c89

    - name: "x64 linux c89"
      os: linux
      compiler: gcc
      env: ARCH=x64 BUILD=c89

    - name: "x64 linux retroarch"
      os: linux
      compiler: gcc-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
      env:
         - ARCH=x64 BUILD=retroarch

script: make -C test ARCH=$ARCH BUILD=$BUILD runtests
