name: C/C++ CI

on:
  push:
    branches: [ master,develop ]
  pull_request:
    branches: [ master,develop ]

jobs:
  linux-x86:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: sudo apt-get install gcc-multilib # bits/libc-header-start.h
    - name: build
      run: make ARCH=x86 BUILD=c89 TARGET=tests
      working-directory: test
    - name: test
      run: ./test
      working-directory: test
